DBSysCmd::Program
static int DBSysCmd.Program.Main(string[] args)
Точка входа программы.Парсит переданные аргументы и выполняет найденные команды.
References DBSysCmd.Program.ChallengeCommand, DBSysCmd.Program.DumpMergeCommand, DBSysCmd.Program.DumpUseCommand, DBSysCmd.Program.LoginCommand, DBSysCmd.Program.LogoutCommand, DBSysCmd.Program.SqlCommand, DBSysCmd.Program.StaffAddCommand, DBSysCmd.Program.StatusCommand, DBSysCmd.Program.TestCommand, DBSysCmd.Program.UpdateStaticCommand.
static void DBSysCmd.Program.StatusCommand(CommandLineApplication command)
Команда проверки текущего состояния программы.Аргументов и опций не требуется.
References DBSysCore.Core.Status.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.LoginCommand(CommandLineApplication command)
Команда для аутентификации текущего пользователя.
References DBSysCore.Core.Login.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.LogoutCommand(CommandLineApplication command)
Комадна для сброса текущей сессии.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.ChallengeCommand(CommandLineApplication command)
Команда для работы с активной последовательностью тестов.Сигнатура комманды: challenge -b|--begin -p|--product="" -c|--challenge-type="" -l|--location="" -d|--description="" challenge -e|--end
References DBSysCore.Core.BeginChallenge, DBSysCore.Core.EndChallenge.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.TestCommand(CommandLineApplication command)
Комадна для работы с активным тестом.
References DBSysCore.Core.Test.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.DumpUseCommand(CommandLineApplication command)
Команда для смены текущего файла дампа.
References DBSysCore.Core.DumpUse.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.DumpMergeCommand(CommandLineApplication command)
Коммадна для объединения нескольких файлов дампов в один.
References DBSysCore.Core.DumpMerge.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.UpdateStaticCommand(CommandLineApplication command)
Команда для загрузки статических данных в текущий файл дампа.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.StaffAddCommand(CommandLineApplication command)
Команда для добавления данных пользователей.
References DBSysCore.Core.AddStaff.
Referenced by DBSysCmd.Program.Main.
static void DBSysCmd.Program.SqlCommand(CommandLineApplication command)
Команда для исполнения SQL запросов над текущим файлом дампа.
References DBSysCore.Core.ExecSQL.
Referenced by DBSysCmd.Program.Main.