UnitTests::DBSysCoreTests
readonly Staff UnitTests.DBSysCoreTests.admin
readonly Staff UnitTests.DBSysCoreTests.oper
readonly Staff UnitTests.DBSysCoreTests.tester
const string UnitTests.DBSysCoreTests.statusTestID
Referenced by UnitTests.DBSysCoreTests.C02_DoTests, UnitTests.DBSysCoreTests.D02_DoTests.
const string UnitTests.DBSysCoreTests.nominalTestID
Referenced by UnitTests.DBSysCoreTests.C02_DoTests, UnitTests.DBSysCoreTests.D02_DoTests.
const string UnitTests.DBSysCoreTests.dumpFile_1
Referenced by UnitTests.DBSysCoreTests.A06_SwitchDumpFile, UnitTests.DBSysCoreTests.E01_CheckDump_1.
const string UnitTests.DBSysCoreTests.dumpFile_2
Referenced by UnitTests.DBSysCoreTests.A06_SwitchDumpFile, UnitTests.DBSysCoreTests.D01_BeginChallenge, UnitTests.DBSysCoreTests.E02_CheckDump_2.
UnitTests.DBSysCoreTests.DBSysCoreTests()
void UnitTests.DBSysCoreTests.A00_CleanUp()
void UnitTests.DBSysCoreTests.A01_SimpleLoginLogout()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.A02_AddStaff_Admin()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.A03_AddStaff_Operator()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.A04_AddStaff_Tester()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.A05_CheckUsersList()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.A06_SwitchDumpFile()
References UnitTests.DBSysCoreTests.CheckFilesAccessory, UnitTests.DBSysCoreTests.dumpFile_1, UnitTests.DBSysCoreTests.dumpFile_2.
void UnitTests.DBSysCoreTests.B01_LoadStaticTests()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.C01_BeginChallenge()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.C02_DoTests()
References UnitTests.DBSysCoreTests.CheckFilesAccessory, UnitTests.DBSysCoreTests.nominalTestID, UnitTests.DBSysCoreTests.statusTestID.
void UnitTests.DBSysCoreTests.C03_EndChallenge()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.D01_BeginChallenge()
References UnitTests.DBSysCoreTests.CheckFilesAccessory, UnitTests.DBSysCoreTests.dumpFile_2.
void UnitTests.DBSysCoreTests.D02_DoTests()
References UnitTests.DBSysCoreTests.CheckFilesAccessory, UnitTests.DBSysCoreTests.nominalTestID, UnitTests.DBSysCoreTests.statusTestID.
void UnitTests.DBSysCoreTests.D03_EndChallenge()
References UnitTests.DBSysCoreTests.CheckFilesAccessory.
void UnitTests.DBSysCoreTests.E01_CheckDump_1()
References UnitTests.DBSysCoreTests.CheckFilesAccessory, UnitTests.DBSysCoreTests.dumpFile_1.
void UnitTests.DBSysCoreTests.E02_CheckDump_2()
References UnitTests.DBSysCoreTests.CheckFilesAccessory, UnitTests.DBSysCoreTests.dumpFile_2.
void UnitTests.DBSysCoreTests.CheckFilesAccessory()
References DBSysCore.Paths.sessionFilename, DBSysCore.Paths.usersFilename.
Referenced by UnitTests.DBSysCoreTests.A01_SimpleLoginLogout, UnitTests.DBSysCoreTests.A02_AddStaff_Admin, UnitTests.DBSysCoreTests.A03_AddStaff_Operator, UnitTests.DBSysCoreTests.A04_AddStaff_Tester, UnitTests.DBSysCoreTests.A05_CheckUsersList, UnitTests.DBSysCoreTests.A06_SwitchDumpFile, UnitTests.DBSysCoreTests.B01_LoadStaticTests, UnitTests.DBSysCoreTests.C01_BeginChallenge, UnitTests.DBSysCoreTests.C02_DoTests, UnitTests.DBSysCoreTests.C03_EndChallenge, UnitTests.DBSysCoreTests.D01_BeginChallenge, UnitTests.DBSysCoreTests.D02_DoTests, UnitTests.DBSysCoreTests.D03_EndChallenge, UnitTests.DBSysCoreTests.E01_CheckDump_1, UnitTests.DBSysCoreTests.E02_CheckDump_2.