DBSysCore::Core
SQLiteConnection DBSysCore.Core.usersConnection
Соединение для пользовательского файла.
Referenced by DBSysCore.Session.Auth, DBSysCore.Core.CloseConnections, DBSysCore.Core.GetAllUsers, DBSysCore.Core.InitializeUserDataConnection, DBSysCore.Core.SaveAllStaff, DBSysCore.Model.Staff.Staff.
SQLiteConnection DBSysCore.Core.dumpConnection
Соединение для текущего файла дампов.
Referenced by DBSysCore.Model.Challenge.Challenge, DBSysCore.Model.ChallengeType.ChallengeType, DBSysCore.Core.CloseConnections, DBSysCore.Model.ControllObject.ControllObject, DBSysCore.Core.EndChallenge, DBSysCore.Model.Methodology.Exists, DBSysCore.Model.Module.Exists, DBSysCore.Model.Requirements.Exists, DBSysCore.Model.Location.Exists, DBSysCore.Model.ChallengeType.Exists, DBSysCore.Model.Staff.Exists, DBSysCore.Model.Staff.Get, DBSysCore.Model.Challenge.GetChallenges, DBSysCore.Model.Module.GetModules, DBSysCore.Model.TestStatic.GetTests, DBSysCore.Model.TestDynamic.GetTestsByQuery, DBSysCore.Core.InitializeConnection, DBSysCore.Core.LoadStaticTests, DBSysCore.Model.Location.Location, DBSysCore.Model.Methodology.Methodology, DBSysCore.Model.Module.Module, DBSysCore.Model.Requirements.Requirements, DBSysCore.Core.RetrieveAllUsers, DBSysCore.Model.Staff.Staff, DBSysCore.Model.TestStatic.TestStatic.
static StatusCode DBSysCore.Core.InitializeConnection()
Инициализирует соединение с текущим файлом дампа.Возвращает false, если соединение прошло успешно.
References DBSysCore.Core.dumpConnection, DBSysCore.Paths.dumpModelFilename.
Referenced by DBSysCore.Core.DumpUse, DBSysCore.Core.EndChallenge, DBSysCore.Core.GetAllChallenges, DBSysCore.Core.GetAllUsers, DBSysCore.Core.GetDynamicTests, DBSysCore.Core.GetModules, DBSysCore.Core.GetStaticTests, DBSysCore.Core.LoadStaticTests, DBSysCore.Core.MapStaticTests.
static StatusCode DBSysCore.Core.InitializeUserDataConnection()
Инициализирует соединение с файлом пользовательких данных.Если файл пользовательских данных не существует - создаёт новый, при этом собирает данные обо всех пользователях из всех возможных источников - файлов дампов, находящихся в папке с программой.
References DBSysCore.Core.RetrieveAllUsers, DBSysCore.Core.usersConnection, DBSysCore.Paths.usersFilename, DBSysCore.Paths.usersModelFilename.
Referenced by DBSysCore.Core.BeginChallenge, DBSysCore.Core.GetAllChallenges, DBSysCore.Core.GetAllUsers, DBSysCore.Core.GetDynamicTests, DBSysCore.Core.Login.
static void DBSysCore.Core.RetrieveAllUsers()
Метод для сбора данных обо всех пользователях из всех файлов дампов в [папке с программой?].
References DBSysCore.Core.dumpConnection, DBSysCore.Paths.dumpsDirectory, DBSysCore.SessionData.filename, DBSysCore.Core.SaveAllStaff, DBSysCore.Session.sessionData.
Referenced by DBSysCore.Core.InitializeUserDataConnection.
static void DBSysCore.Core.SaveAllStaff(List< Staff > staffList)
Производит запись информации обо всех предоставленных пользователях в пользовательский файл.
References DBSysCore.Core.usersConnection.
Referenced by DBSysCore.Core.RetrieveAllUsers.
static void DBSysCore.Core.CloseConnections()
Закрывает все открытые соединения.
References DBSysCore.Core.dumpConnection, DBSysCore.Core.usersConnection.
Referenced by DBSysCore.Core.BeginChallenge, DBSysCore.Core.DumpUse, DBSysCore.Core.EndChallenge, DBSysCore.Core.GetAllChallenges, DBSysCore.Core.GetAllUsers, DBSysCore.Core.GetDynamicTests, DBSysCore.Core.GetModules, DBSysCore.Core.GetStaticTests, DBSysCore.Core.LoadStaticTests, DBSysCore.Core.Login, DBSysCore.Core.MapStaticTests, DBSysCore.Core.Test.
static StatusCode DBSysCore.Core.HasOTKStaff(int id, out bool flag)
References DBSysCore.Core.GetAllUsers, DBSysCore.Model.Staff.id.
Referenced by DBSysCore.Core.BeginChallenge.
static string DBSysCore.Core.GenerateReportFileName(Challenge challenge)
static void DBSysCore.Core._ExecSQL(string query)
Referenced by DBSysCore.Core.LoadStaticTests.
static void DBSysCore.Core.MergeFiles(SQLiteConnection connection, string source)
Метод для объединения данных из файла с названием source по переданному соединению.
Referenced by DBSysCore.Core.DumpMerge.
static StatusCode DBSysCore.Core.GetAllUsers(out List< Staff > staffList)
Выделяет всех сохранённых пользователей из [пользовательской?] базы данных.
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Core.InitializeUserDataConnection, DBSysCore.Core.usersConnection.
Referenced by DBSysCore.Core.HasOTKStaff.
static StatusCode DBSysCore.Core.GetAllChallenges(out List< Challenge > challengeList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Core.InitializeUserDataConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.Session.RequireGrants.
static StatusCode DBSysCore.Core.GetModules(out List< Module > modulesList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
static StatusCode DBSysCore.Core.GetStaticTests(out List< TestStatic > testsList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
Referenced by DBSysReport.AppForm.modeComboBox_SelectedIndexChanged.
static StatusCode DBSysCore.Core.GetDynamicTests(out List< TestDynamic > testsList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Core.InitializeUserDataConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
static StatusCode DBSysCore.Core.GetDynamicTests(Challenge challenge, out List< TestDynamic > testsList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
static StatusCode DBSysCore.Core.GetDynamicTests(DateTime beginDate, DateTime endDate, out List< TestDynamic > testsList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
static StatusCode DBSysCore.Core.MapStaticTests(List< TestDynamic > testsDynamicList, out List< TestStatic > testsStaticList)
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection.
static StatusCode DBSysCore.Core.Status(out string status)
Передает данные состояния программы в строку status.
References DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.sessionData.
Referenced by DBSysCmd.Program.StatusCommand.
static StatusCode DBSysCore.Core.Login(string login, string password)
Производит авторизацию пользователя по введённому логину и паролю.
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeUserDataConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.Paths.usersFilename.
Referenced by DBSysCmd.Program.LoginCommand.
static StatusCode DBSysCore.Core.Logout()
Производит сброс текущего авторизорованного пользователя.
static StatusCode DBSysCore.Core.BeginChallenge(string productName, string coName, string coSerialNumber, string coDecNumber, int staffOTKId, string coParent, string challengeTypeName, string locationName, string description="")
Иниализирует новое испытание.
References DBSysCore.Core.CloseConnections, DBSysCore.Core.HasOTKStaff, DBSysCore.Core.InitializeUserDataConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.Session.IsLoggedInAsVirtualAdmin, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
Referenced by DBSysCmd.Program.ChallengeCommand.
static StatusCode DBSysCore.Core.EndChallenge()
Завершает и сохраняет текущее испытание.
References DBSysCore.Core.CloseConnections, DBSysCore.Core.dumpConnection, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
Referenced by DBSysCmd.Program.ChallengeCommand.
static StatusCode DBSysCore.Core.Test(string tsIndex, bool status, decimal nominal, decimal actualValue, decimal delta, decimal boundaryValue)
Иниализирует новый тест. (test_dynamic)
References DBSysCore.Core.CloseConnections, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
Referenced by DBSysCmd.Program.TestCommand.
static StatusCode DBSysCore.Core.Test(string tsIndex, bool status)
References DBSysCore.Core.CloseConnections, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
static StatusCode DBSysCore.Core.LoadStaticTests()
Загружает статические данные в текущий файл дампа.
References DBSysCore.Core._ExecSQL, DBSysCore.Core.CloseConnections, DBSysCore.Core.dumpConnection, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData, DBSysCore.Paths.staticDataTable.
static StatusCode DBSysCore.Core.DumpUse(string filepath)
Метод для смены рабочего файла дампа.
References DBSysCore.Core.CloseConnections, DBSysCore.Core.InitializeConnection, DBSysCore.Session.IsLoggedIn, DBSysCore.Session.RequireGrants.
Referenced by DBSysCmd.Program.DumpUseCommand.
static StatusCode DBSysCore.Core.DumpMerge(string dest, string[] src)
Метод для объединения нескольких файлов дампов в один.
References DBSysCore.Session.IsLoggedIn, DBSysCore.Core.MergeFiles, DBSysCore.Session.RequireGrants.
Referenced by DBSysCmd.Program.DumpMergeCommand.
static StatusCode DBSysCore.Core.GenerateReport(Challenge challenge, out string resultFileName)
References DBSysCore.Model.Challenge.controllObject, DBSysCore.Model.TestDynamic.GetTests, DBSysCore.Session.IsLoggedIn, DBSysCore.Model.ControllObject.name, DBSysCore.Model.ControllObject.product, DBSysCore.Session.RequireGrants, DBSysCore.Model.ControllObject.serialNumber, DBSysCore.Model.TestDynamic.status, DBSysCore.Model.TestStatic.unit.
Referenced by DBSysReport.AppForm.createReportButton_Click.
static StatusCode DBSysCore.Core.AddStaff(string surname, string firstName, string patronymicName, string postName, string departmentName, string login, string password)
Метод для добавления учётной записи для пользователя.При попытке создать пользователя с существующими фамилией, именем и отчеством то происходит смена логина и пароля.
References DBSysCore.Session.IsLoggedIn, DBSysCore.Session.RequireGrants.
Referenced by DBSysCmd.Program.StaffAddCommand.
static StatusCode DBSysCore.Core.UpdateStaff(Staff staff)
References DBSysCore.Session.IsLoggedIn, DBSysCore.SessionData.programState, DBSysCore.Session.RequireGrants, DBSysCore.Session.sessionData.
static StatusCode DBSysCore.Core.ExecSQL(string query, out string output)
References DBSysCore.Session.IsLoggedIn, DBSysCore.Session.RequireGrants.
Referenced by DBSysCmd.Program.SqlCommand.
static StatusCode DBSysCore.Core.GetFPGAVersion(Challenge challenge, out string version)
Referenced by DBSysReport.AppForm.challengeDates_SelectedIndexChanged.