DBSysReport::AppForm
List<Staff> DBSysReport.AppForm.allStaff
Referenced by DBSysReport.AppForm.UpdateUsersList.
Staff DBSysReport.AppForm.newStaff
Referenced by DBSysReport.AppForm.GenerateNewStaff, DBSysReport.AppForm.setEmployerDataButton_Click, DBSysReport.AppForm.UpdateUsersList, DBSysReport.AppForm.usersList_SelectedIndexChanged.
List<Challenge> DBSysReport.AppForm.allChallenges
Referenced by DBSysReport.AppForm.challengeDates_SelectedIndexChanged, DBSysReport.AppForm.InitReportPanel.
System.ComponentModel.IContainer DBSysReport.AppForm.components
Required designer variable.
Referenced by DBSysReport.AppForm.Dispose.
System.Windows.Forms.MenuStrip DBSysReport.AppForm.appMenu
System.Windows.Forms.ToolStripMenuItem DBSysReport.AppForm.exitMenuOption
System.Windows.Forms.ToolStripMenuItem DBSysReport.AppForm.infoToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem DBSysReport.AppForm.aboutMenuOption
System.Windows.Forms.ToolStripMenuItem DBSysReport.AppForm.infoToolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem DBSysReport.AppForm.aboutToolStripMenuItem1
System.Windows.Forms.Panel DBSysReport.AppForm.userPanel
System.Windows.Forms.ListBox DBSysReport.AppForm.usersList
Referenced by DBSysReport.AppForm.setEmployerDataButton_Click, DBSysReport.AppForm.usersList_SelectedIndexChanged.
System.Windows.Forms.Panel DBSysReport.AppForm.adminPanel
System.Windows.Forms.GroupBox DBSysReport.AppForm.usersPanelBox
System.Windows.Forms.GroupBox DBSysReport.AppForm.dumpFilePanelBox
System.Windows.Forms.TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel3
System.Windows.Forms.Label DBSysReport.AppForm.label9
System.Windows.Forms.Label DBSysReport.AppForm.label10
System.Windows.Forms.GroupBox DBSysReport.AppForm.groupBox2
Referenced by DBSysReport.AppForm.AppForm_Load.
System.Windows.Forms.TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel4
System.Windows.Forms.TextBox DBSysReport.AppForm.currentDumpFileInput
System.Windows.Forms.TextBox DBSysReport.AppForm.staticDataFileInput
System.Windows.Forms.SplitContainer DBSysReport.AppForm.splitContainer1
Referenced by DBSysReport.AppForm.InitializeComponent.
System.Windows.Forms.GroupBox DBSysReport.AppForm.groupBox4
System.Windows.Forms.GroupBox DBSysReport.AppForm.sqlPanelBox
System.Windows.Forms.GroupBox DBSysReport.AppForm.reportPanelBox
System.Windows.Forms.TabControl DBSysReport.AppForm.reportTabControl
System.Windows.Forms.TabPage DBSysReport.AppForm.tabPage1
System.Windows.Forms.TabPage DBSysReport.AppForm.tabPage2
GroupBox DBSysReport.AppForm.groupBox5
TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel7
TextBox DBSysReport.AppForm.passwordInput
Referenced by DBSysReport.AppForm.setEmployerDataButton_Click.
Label DBSysReport.AppForm.label3
TextBox DBSysReport.AppForm.loginInput
Label DBSysReport.AppForm.label8
TextBox DBSysReport.AppForm.departmentInput
TextBox DBSysReport.AppForm.patronymicNameInput
Referenced by DBSysReport.AppForm.setEmployerDataButton_Click.
TextBox DBSysReport.AppForm.nameInput
Referenced by DBSysReport.AppForm.setEmployerDataButton_Click.
TextBox DBSysReport.AppForm.surnameInput
Referenced by DBSysReport.AppForm.setEmployerDataButton_Click.
Label DBSysReport.AppForm.label6
Label DBSysReport.AppForm.label5
ComboBox DBSysReport.AppForm.postInput
Referenced by DBSysReport.AppForm.InitPostsItems.
Label DBSysReport.AppForm.label4
Label DBSysReport.AppForm.label7
Label DBSysReport.AppForm.label2
Button DBSysReport.AppForm.setEmployerDataButton
Button DBSysReport.AppForm.selectDumpFileButton
Button DBSysReport.AppForm.selectStaticDataFileButton
Button DBSysReport.AppForm.mergeButton
Button DBSysReport.AppForm.selectSourceButton
Button DBSysReport.AppForm.button1
TextBox DBSysReport.AppForm.sourceDumpFileInput
TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel1
TextBox DBSysReport.AppForm.sqlOutput
TextBox DBSysReport.AppForm.sqlInput
TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel2
Button DBSysReport.AppForm.addEmployerDataButton
SplitContainer DBSysReport.AppForm.splitContainer2
Referenced by DBSysReport.AppForm.InitializeComponent.
TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel6
Label DBSysReport.AppForm.label1
Button DBSysReport.AppForm.createReportButton
Label DBSysReport.AppForm.label11
ComboBox DBSysReport.AppForm.reportTypeComboBox
ListBox DBSysReport.AppForm.challengeDates
Referenced by DBSysReport.AppForm.challengeDates_SelectedIndexChanged, DBSysReport.AppForm.createReportButton_Click.
SplitContainer DBSysReport.AppForm.splitContainer3
Referenced by DBSysReport.AppForm.InitializeComponent.
TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel8
Label DBSysReport.AppForm.label13
Button DBSysReport.AppForm.showStatisticsButton
TableLayoutPanel DBSysReport.AppForm.statisticDateInputPanel
Label DBSysReport.AppForm.label14
Label DBSysReport.AppForm.label15
DateTimePicker DBSysReport.AppForm.beginDateTimePicker
DateTimePicker DBSysReport.AppForm.endDateTimePicker
AxAcroPDFLib.AxAcroPDF DBSysReport.AppForm.pdfViewer
Referenced by DBSysReport.AppForm.InitializeComponent.
Label DBSysReport.AppForm.label16
System.Windows.Forms.DataVisualization.Charting.Chart DBSysReport.AppForm.moduleStatsChart
Referenced by DBSysReport.AppForm.InitializeComponent.
CheckBox DBSysReport.AppForm.allTimeCheckBox
Referenced by DBSysReport.AppForm.allTimeCheckBox_CheckedChanged, DBSysReport.AppForm.GrabDataForStatistics, DBSysReport.AppForm.UpdateStatisticsDataLables.
TableLayoutPanel DBSysReport.AppForm.statisticTableCommand
System.Windows.Forms.DataVisualization.Charting.Chart DBSysReport.AppForm.productStatsChart
Referenced by DBSysReport.AppForm.InitializeComponent.
Label DBSysReport.AppForm.label17
Label DBSysReport.AppForm.periodLabel1
Label DBSysReport.AppForm.label21
Label DBSysReport.AppForm.periodLabel3
Label DBSysReport.AppForm.periodLabel2
Label DBSysReport.AppForm.label19
TableLayoutPanel DBSysReport.AppForm.statTable_Product
Referenced by DBSysReport.AppForm.ShowStatistics.
Label DBSysReport.AppForm.label26
Label DBSysReport.AppForm.label25
Label DBSysReport.AppForm.label24
TableLayoutPanel DBSysReport.AppForm.statTable_Command
Referenced by DBSysReport.AppForm.ShowStatistics.
Label DBSysReport.AppForm.label29
Label DBSysReport.AppForm.label30
Label DBSysReport.AppForm.label31
TableLayoutPanel DBSysReport.AppForm.statTable_Module
Referenced by DBSysReport.AppForm.ShowStatistics.
Label DBSysReport.AppForm.label23
Label DBSysReport.AppForm.label27
Label DBSysReport.AppForm.label28
System.Windows.Forms.DataVisualization.Charting.Chart DBSysReport.AppForm.commandStatsChart
Referenced by DBSysReport.AppForm.InitializeComponent.
Label DBSysReport.AppForm.label32
ComboBox DBSysReport.AppForm.moduleComboBox
Referenced by DBSysReport.AppForm.modeComboBox_SelectedIndexChanged, DBSysReport.AppForm.moduleComboBox_SelectedIndexChanged, DBSysReport.AppForm.ShowStatistics.
ComboBox DBSysReport.AppForm.commandComboBox
Referenced by DBSysReport.AppForm.modeComboBox_SelectedIndexChanged, DBSysReport.AppForm.ShowStatistics.
Label DBSysReport.AppForm.label18
ComboBox DBSysReport.AppForm.modeComboBox
Referenced by DBSysReport.AppForm.modeComboBox_SelectedIndexChanged, DBSysReport.AppForm.moduleComboBox_SelectedIndexChanged, DBSysReport.AppForm.ShowStatistics.
Label DBSysReport.AppForm.label20
Label DBSysReport.AppForm.label22
Label DBSysReport.AppForm.label33
Label DBSysReport.AppForm.label34
Label DBSysReport.AppForm.label35
SplitContainer DBSysReport.AppForm.mainSplitContainer
Referenced by DBSysReport.AppForm.InitializeComponent.
GroupBox DBSysReport.AppForm.databaseControllPanel
TableLayoutPanel DBSysReport.AppForm.tableLayoutPanel10
ToolStripMenuItem DBSysReport.AppForm.ToolStripMenuItem
ToolStripMenuItem DBSysReport.AppForm.ToolStripMenuItem
ToolStripMenuItem DBSysReport.AppForm.ToolStripMenuItem
Label DBSysReport.AppForm.label36
Label DBSysReport.AppForm.ChallengeDataLabel
TabControl DBSysReport.AppForm.tabControl1
TabPage DBSysReport.AppForm.tabPage3
TableLayoutPanel DBSysReport.AppForm.statisticTableProduct
TabPage DBSysReport.AppForm.tabPage4
TableLayoutPanel DBSysReport.AppForm.statisticTableModule
TabPage DBSysReport.AppForm.tabPage5
ToolStripMenuItem DBSysReport.AppForm.ToolStripMenuItem
DBSysReport.AppForm.AppForm()
References DBSysReport.AppForm.InitializeComponent.
void DBSysReport.AppForm.GenerateNewStaff()
References DBSysReport.AppForm.newStaff.
Referenced by DBSysReport.AppForm.UpdateUsersList.
void DBSysReport.AppForm.InitPostsItems()
References DBSysCore.Session.GrantsString, DBSysReport.AppForm.postInput.
Referenced by DBSysReport.AppForm.AppForm_Load.
void DBSysReport.AppForm.UpdateUsersList()
References DBSysReport.AppForm.allStaff, DBSysReport.AppForm.GenerateNewStaff, DBSysReport.AppForm.newStaff.
Referenced by DBSysReport.AppForm.addEmployerDataButton_Click, DBSysReport.AppForm.AppForm_Load.
void DBSysReport.AppForm.AppForm_Load(object sender, EventArgs e)
References DBSysReport.AppForm.groupBox2, DBSysReport.AppForm.InitModuleNames, DBSysReport.AppForm.InitPostsItems, DBSysReport.AppForm.InitReportPanel, DBSysCore.Session.IsLoggedIn, DBSysCore.Session.RequireGrants, DBSysReport.AppForm.UpdateUsersList.
void DBSysReport.AppForm.InitReportPanel()
References DBSysReport.AppForm.allChallenges.
Referenced by DBSysReport.AppForm.AppForm_Load.
void DBSysReport.AppForm.InitModuleNames()
Referenced by DBSysReport.AppForm.AppForm_Load.
void DBSysReport.AppForm.LogoutAndExit(object sender, EventArgs e)
void DBSysReport.AppForm.usersList_SelectedIndexChanged(object sender, EventArgs e)
References DBSysReport.AppForm.newStaff, DBSysReport.AppForm.usersList.
void DBSysReport.AppForm.setEmployerDataButton_Click(object sender, EventArgs e)
References DBSysCore.Model.Staff.firstName, DBSysReport.AppForm.nameInput, DBSysReport.AppForm.newStaff, DBSysReport.AppForm.passwordInput, DBSysCore.Model.Staff.patronymicName, DBSysReport.AppForm.patronymicNameInput, DBSysCore.Model.Staff.post, DBSysCore.Model.Staff.surname, DBSysReport.AppForm.surnameInput, DBSysReport.AppForm.usersList.
Referenced by DBSysReport.AppForm.addEmployerDataButton_Click.
void DBSysReport.AppForm.selectDumpFileButton_Click(object sender, EventArgs e)
void DBSysReport.AppForm.LoadStaticTests(object sender, EventArgs e)
void DBSysReport.AppForm.InputSQLCommand(object sender, KeyPressEventArgs e)
void DBSysReport.AppForm.addEmployerDataButton_Click(object sender, EventArgs e)
References DBSysReport.AppForm.setEmployerDataButton_Click, DBSysReport.AppForm.UpdateUsersList.
void DBSysReport.AppForm.challengeDates_SelectedIndexChanged(object sender, EventArgs e)
References DBSysReport.AppForm.allChallenges, DBSysReport.AppForm.challengeDates, DBSysCore.Core.GetFPGAVersion.
void DBSysReport.AppForm.createReportButton_Click(object sender, EventArgs e)
References DBSysReport.AppForm.challengeDates, DBSysCore.Core.GenerateReport.
bool DBSysReport.AppForm.GrabDataForStatistics(out List< TestDynamic > testsDynamicList, out List< TestStatic > testsStaticList, out List< int > modulesFailsStats, out List< int > commandsFailsStats)
References DBSysReport.AppForm.allTimeCheckBox, DBSysCore.Model.TestDynamic.status.
Referenced by DBSysReport.AppForm.ShowStatistics.
void DBSysReport.AppForm.UpdateStatisticsDataLables()
References DBSysReport.AppForm.allTimeCheckBox.
Referenced by DBSysReport.AppForm.ShowStatistics.
Label DBSysReport.AppForm.CreateTableLabel(string text)
Referenced by DBSysReport.AppForm.ShowStatistics.
void DBSysReport.AppForm.ClearTable(TableLayoutPanel table, int columnsCount, int itemsCount)
Referenced by DBSysReport.AppForm.ShowStatistics.
void DBSysReport.AppForm.ShowStatistics(object sender, EventArgs e)
References DBSysCore.Model.TestDynamic.actualValue, DBSysCore.Model.TestDynamic.beginTime, DBSysCore.Model.TestDynamic.boundaryValue, DBSysCore.Model.TestDynamic.challenge, DBSysReport.AppForm.ClearTable, DBSysReport.AppForm.commandComboBox, DBSysCore.Model.Challenge.controllObject, DBSysReport.AppForm.CreateTableLabel, DBSysReport.AppForm.GrabDataForStatistics, DBSysCore.Model.TestStatic.mode, DBSysReport.AppForm.modeComboBox, DBSysReport.AppForm.moduleComboBox, DBSysCore.Model.TestDynamic.nominal, DBSysCore.Model.ControllObject.serialNumber, DBSysReport.AppForm.statTable_Command, DBSysReport.AppForm.statTable_Module, DBSysReport.AppForm.statTable_Product, DBSysCore.Model.TestDynamic.status, DBSysCore.Model.TestStatic.tsIndex, DBSysCore.Model.TestStatic.unit, DBSysReport.AppForm.UpdateStatisticsDataLables.
void DBSysReport.AppForm.allTimeCheckBox_CheckedChanged(object sender, EventArgs e)
References DBSysReport.AppForm.allTimeCheckBox.
void DBSysReport.AppForm.moduleComboBox_SelectedIndexChanged(object sender, EventArgs e)
References DBSysCore.Model.Module.id, DBSysCore.Model.TestStatic.mode, DBSysReport.AppForm.modeComboBox, DBSysCore.Model.TestStatic.module, DBSysReport.AppForm.moduleComboBox.
void DBSysReport.AppForm.modeComboBox_SelectedIndexChanged(object sender, EventArgs e)
References DBSysReport.AppForm.commandComboBox, DBSysCore.Core.GetStaticTests, DBSysCore.Model.Module.id, DBSysCore.Model.TestStatic.mode, DBSysReport.AppForm.modeComboBox, DBSysCore.Model.TestStatic.module, DBSysReport.AppForm.moduleComboBox.
void DBSysReport.AppForm.commandComboBox_SelectedIndexChanged(object sender, EventArgs e)
void DBSysReport.AppForm.ShowDatabasePanel(object sender, EventArgs e)
void DBSysReport.AppForm.ShowReportPanel(object sender, EventArgs e)
void DBSysReport.AppForm.ShowBothPanels(object sender, EventArgs e)
void DBSysReport.AppForm.aboutToolStripMenuItem1_Click(object sender, EventArgs e)
void DBSysReport.AppForm.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References DBSysReport.AppForm.commandStatsChart, DBSysReport.AppForm.mainSplitContainer, DBSysReport.AppForm.moduleStatsChart, DBSysReport.AppForm.pdfViewer, DBSysReport.AppForm.productStatsChart, DBSysReport.AppForm.splitContainer1, DBSysReport.AppForm.splitContainer2, DBSysReport.AppForm.splitContainer3.
Referenced by DBSysReport.AppForm.AppForm.
override void DBSysReport.AppForm.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References DBSysReport.AppForm.components.