CREATE TABLE IF NOT EXISTS staff (
  id INT NOT NULL,
  surname VARCHAR(64) NOT NULL,
  first_name VARCHAR(64) NOT NULL,
  patronymic_name VARCHAR(64) NULL DEFAULT NULL,
  post VARCHAR(16) NOT NULL,
  department VARCHAR(64) NOT NULL,
  login VARCHAR(20) NOT NULL,
  password VARCHAR(64) NOT NULL,
  PRIMARY KEY (id)
);