DBSysCore::Session
SessionData DBSysCore.Session.sessionData
Данные текущей сессии.
Referenced by DBSysCore.Core.BeginChallenge, DBSysCore.Session.Close, DBSysCore.Core.EndChallenge, DBSysCore.Core.GetDynamicTests, DBSysCore.Session.GetGrants, DBSysCore.Core.GetModules, DBSysCore.Core.GetStaticTests, DBSysCore.Session.GetUserName, DBSysCore.Core.LoadStaticTests, DBSysCore.Session.Open, DBSysCore.Core.RetrieveAllUsers, DBSysCore.Session.SaveCurrentChallenge, DBSysCore.Core.Status, DBSysCore.Core.Test, DBSysCore.Core.UpdateStaff.
Staff DBSysCore.Session.virtualAdmin
Referenced by DBSysCore.Session.Auth.
bool DBSysCore.Session.opened
Referenced by DBSysCore.Session.Close, DBSysCore.Session.Open.
static void DBSysCore.Session.Open()
Считывает данные последней сессии из файла сессии.Если файл сессии не существует, то будут использованы данные сессии по-умолчанию: - пользователь не авторизован - состояние программы - авторизация - файл дампа - "dump.db"
References DBSysCore.Session.GenerateDefaultSessionData, DBSysCore.Session.opened, DBSysCore.Session.sessionData, DBSysCore.Paths.sessionFilename.
Referenced by DBSysCore.Session.Auth, DBSysCore.Session.GetCurrentWorkingDumpFileName, DBSysCore.Session.GetCurrentWorkingDumpFileNameWithPath, DBSysCore.Session.GetGrants, DBSysCore.Session.GetUserName, DBSysCore.Session.IsLoggedIn, DBSysCore.Session.IsLoggedInAsVirtualAdmin, DBSysCore.Session.RequireGrants, DBSysCore.Session.SaveCurrentChallenge.
static string DBSysCore.Session.GetCurrentWorkingDumpFileName()
References DBSysCore.Session.Open.
static string DBSysCore.Session.GetCurrentWorkingDumpFileNameWithPath()
References DBSysCore.Session.Open.
static string DBSysCore.Session.GetUserName()
Возвращает форматированное имя текущего пользователя, или "unatorized", если пользователь не авторизован.Формат вывода: Фамилия И.
References DBSysCore.Session.Open, DBSysCore.Session.sessionData, DBSysCore.SessionData.staff.
static SessionData DBSysCore.Session.GenerateDefaultSessionData()
Возвращает данные сессии по-умолчанию: - пользователь не авторизован - состояние программы - авторизация - файл дампа - "dump.db"
Referenced by DBSysCore.Session.Open.
static bool DBSysCore.Session.IsLoggedIn()
Возвращает true, если данные последней сессии содержат информацию о пользователе.
References DBSysCore.Session.Open.
Referenced by DBSysCore.Core.AddStaff, DBSysCore.Core.BeginChallenge, DBSysCore.Core.DumpMerge, DBSysCore.Core.DumpUse, DBSysCore.Core.EndChallenge, DBSysCore.Core.ExecSQL, DBSysCore.Core.GenerateReport, DBSysCore.Core.GetAllChallenges, DBSysCore.Core.GetDynamicTests, DBSysCore.Core.GetModules, DBSysCore.Core.GetStaticTests, DBSysCore.Core.LoadStaticTests, DBSysCore.Core.Login, DBSysCore.Session.RequireGrants, DBSysCore.Core.Status, DBSysCore.Core.Test, DBSysCore.Core.UpdateStaff.
static bool DBSysCore.Session.IsLoggedInAsVirtualAdmin()
References DBSysCore.Session.Open.
Referenced by DBSysCore.Core.BeginChallenge.
static UserGrants DBSysCore.Session.GetGrants()
Возвращает объект UserGrants с правами текущего авторизированного пользователя.
References DBSysCore.Session.Open, DBSysCore.Session.sessionData, DBSysCore.SessionData.staff.
Referenced by DBSysCore.Session.RequireGrants.
static string DBSysCore.Session.GrantsString(UserGrants grants)
Возвращает строку-представление переданного объекта прав. "admin" | "operator" | "tester" | "unauthorized"
static bool DBSysCore.Session.RequireGrants(UserGrants grants)
Возвращает true, если права текущего пользователя включают в себя переданные права.
References DBSysCore.Session.GetGrants, DBSysCore.Session.IsLoggedIn, DBSysCore.Session.Open.
Referenced by DBSysCore.Core.AddStaff, DBSysCore.Core.BeginChallenge, DBSysCore.Core.DumpMerge, DBSysCore.Core.DumpUse, DBSysCore.Core.EndChallenge, DBSysCore.Core.ExecSQL, DBSysCore.Core.GenerateReport, DBSysCore.Core.GetAllChallenges, DBSysCore.Core.GetDynamicTests, DBSysCore.Core.GetModules, DBSysCore.Core.GetStaticTests, DBSysCore.Core.LoadStaticTests, DBSysCore.Core.Test, DBSysCore.Core.UpdateStaff.
static StatusCode DBSysCore.Session.Auth(string login, string password)
Авторизирует пользователя по переданным логину и паролю. Возвращает 0, если авторизация прошла успешно.Использует данные для входа из файла пользователей.Гарантируется, что файл пользовательских данных будет создан до вызова данного метода.Сохраняет инофрмацию о текущем аутентифицированном пользователе в данных текущей сессии.Переводит текущее состояние программы в рабочее.
References DBSysCore.Session.Open, DBSysCore.Core.usersConnection, DBSysCore.Utils.VerifyHash, DBSysCore.Session.virtualAdmin.
static void DBSysCore.Session.Logout()
Сбрасывает данные текущей сессии. В том числе информацию о текущем пользователе, активной последовательности тестов и о самих тестах.Переводит текущее состояние программы в ожидание аутентификации.
static void DBSysCore.Session.SwitchDumpFile(string filename)
static StatusCode DBSysCore.Session.SaveCurrentChallenge(SQLiteConnection connection)
Сохраняет текущую последовательность тестов по переданному соединению. При этом данные текущей последовательности тестов сбрасываются в данных текущей сессии.Переданное соединение должно быть открыто.Возвращает false, если запись прошла успешно.
References DBSysCore.SessionData.activeTests, DBSysCore.Session.Open, DBSysCore.Session.sessionData.
static void DBSysCore.Session.Close()
Сохраняет данные текущей сессии в файл данных последней сессии.
References DBSysCore.Session.opened, DBSysCore.Session.sessionData, DBSysCore.Paths.sessionFilename.